# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# ls aliases
alias ll='ls -l'
alias lla='ls -l -A'
alias la='ls -A'

# neovim
alias vim='nvim'

alias notes='cd ~/notes & vim .'
